[tool.bumpversion]
current_version = "1.7.0a1"
parse = '''
     (?P<major>[\d]+) # major version number
     \.(?P<minor>[\d]+) # minor version number
     \.(?P<patch>[\d]+) # patch version number
     (?P<prerelease>  # optional pre-release - ex: a1, b2, rc25
     (?P<prekind>a|b|rc) # pre-release type
     (?P<num>[\d]+) # pre-release version number
     )?
     ( # optional nightly release indicator
     \.(?P<nightly>dev[0-9]+) # ex: .dev02142023
     )? # expected matches: `1.15.0`, `1.5.0a11`, `1.5.0a1.dev123`, `1.5.0.dev123457`, expected failures: `1`, `1.5`, `1.5.2-a1`, `text1.5.0`
'''
serialize = [
     "{major}.{minor}.{patch}{prekind}{num}.{nightly}",
     "{major}.{minor}.{patch}.{nightly}",
     "{major}.{minor}.{patch}{prekind}{num}",
     "{major}.{minor}.{patch}",
]
commit = false
tag = false

[tool.bumpversion.parts.prekind]
first_value = "a"
optional_value = "final"
values = [
     "a",
     "b",
     "rc",
     "final",
]

[tool.bumpversion.parts.num]
first_value = "1"

[[tool.bumpversion.files]]
filename = "setup.py"

[[tool.bumpversion.files]]
filename = "dbt/adapters/mysql/__version__.py"

[[tool.bumpversion.files]]
filename = "dbt/adapters/mysql5/__version__.py"

[[tool.bumpversion.files]]
filename = "dbt/adapters/mariadb/__version__.py"

[[tool.bumpversion.files]]
filename = "dev-requirements.txt"
parse = '''
     (?P<major>[\d]+) # major version number
     \.(?P<minor>[\d]+) # minor version number
     .latest
'''
serialize = ["{major}.{minor}.latest"]
